# Generated by Django 2.2.10 on 2020-03-11 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ZumiaShop', '0004_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='slug',
        ),
    ]
