# Generated by Django 2.2.10 on 2020-03-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZumiaShop', '0005_remove_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
