# Generated by Django 2.2.10 on 2020-03-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZumiaShop', '0006_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='This is a text description hsbjbsdcdschbdchbdshbdchdchdhdhgdchdhdshjhjd'),
            preserve_default=False,
        ),
    ]
